Handle reading CSV files with missing trailing empty fields.
Such CSV files are not produced by matholymp, but may arise as inputs
to bulk registration generated by external software.  Without the fix
to set restval='' when reading a CSV file, such files result in an
exception "AttributeError: 'NoneType' object has no attribute 'strip'"
in the bulk registration code.